default_context:
    full_name: "Andrew Gaitskell"
    email: "andrew@gaitskell.com"
    github_username: "andrewcgaitskell"
cookiecutters_dir: "/home/user/cookie_cutter_dir/"
replay_dir: "/home/user/replay_dir/"
abbreviations:
    pp: https://github.com/andrewcgaitskell/publish_dash_component.git
    gh: https://github.com/{0}.git
    bb: https://bitbucket.org/{0}
